version: '3'

services:

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: on-failure
    command:
    - "-b"
    - "0.0.0.0"
    - "-Dkeycloak.migration.action=import"
    - "-Dkeycloak.migration.provider=dir"
    - "-Dkeycloak.migration.dir=/config/"
    - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
    - ./config:/config/
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=password
    - DB_VENDOR=postgres
    - DB_USER=admin
    - DB_PASSWORD=password
    - DB_ADDR=192.168.1.203
    - DB_PORT=5431
    - DB_DATABASE=keycloakdb
    ports:
    - "8081:8080"
    depends_on:
    - keycloak-db

  keycloak-db:
    image: postgres
    container_name: keycloak-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloakdb
    ports:
      - 5431:5432
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: